; Please do not edit this file! If this file is modified, results are unpredictable.
[ MEGAinfo ]
ver=12.0.11
[ DataSettings ]
datatype=snProtein
MissingBaseSymbol=?
IdenticalBaseSymbol=.
GapSymbol=-
LabelSeparator=:
[ ProcessTypes ]
ppBNJ=true
[ AnalysisSettings ]
Analysis=Phylogeny Reconstruction
Scope=All Selected Taxa
Statistical Method=Neighbor-joining
Test of Phylogeny=Bootstrap method
No. of Bootstrap Replications=500
Model/Method=p-distance
Rates among Sites=Uniform Rates
Pattern among Lineages=Same (Homogeneous)
Gaps/Missing Data Treatment=Pairwise deletion
